/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nmproto;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.Future;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.asynchttpclient.*;
import org.asynchttpclient.Dsl.*;

/**
 *
 * @author kkch
 */
public class MainWnd extends javax.swing.JFrame {

    SettingFrm _settingFrm;
    /**
     * Creates new form MainWnd
     */
    public MainWnd() {
        this._settingFrm = new SettingFrm();
        initComponents();
        
    }
    
    /**
     
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _btn_setting = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        _txt_result = new javax.swing.JTextArea();
        _btn_get_server_info = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        _btn_setting.setText("Settings");
        _btn_setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_settingActionPerformed(evt);
            }
        });

        _txt_result.setColumns(20);
        _txt_result.setLineWrap(true);
        _txt_result.setRows(5);
        _txt_result.setWrapStyleWord(true);
        jScrollPane1.setViewportView(_txt_result);

        _btn_get_server_info.setText("Get game server info");
        _btn_get_server_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _btn_get_server_infoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_btn_get_server_info)
                    .addComponent(_btn_setting)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_btn_setting)
                .addGap(18, 18, 18)
                .addComponent(_btn_get_server_info)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _btn_settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_settingActionPerformed
        this._settingFrm.setVisible(true);
    }//GEN-LAST:event__btn_settingActionPerformed
      
    
    private void _btn_get_server_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__btn_get_server_infoActionPerformed
      
        AsyncHttpClient client = Dsl.asyncHttpClient();
        String strUrl = "http://session-api.netmarble.com/" + "sessions?gameCode=" + GameSetting.gameCode;
        
        BoundRequestBuilder builder = client.prepareGet(strUrl);
        builder.setHeader("gameToken", GameSetting.gameToken);
        builder.setHeader("NMPlayerID", GameSetting.playerId);        
        Future<Response> future = client.executeRequest(builder.build());
        System.out.println("waiting for response");
        Response response;
        try {
            response = future.get();
            int status  = response.getStatusCode();       
            String body =  response.getResponseBody();
            _txt_result.setText(body);
            
        } catch (InterruptedException ex) {
            Logger.getLogger(MainWnd.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExecutionException ex) {
            Logger.getLogger(MainWnd.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event__btn_get_server_infoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton _btn_get_server_info;
    private javax.swing.JButton _btn_setting;
    private javax.swing.JTextArea _txt_result;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}



